import json
import httpx
from typing import Any
from app.core.config import settings


class LLMAdapter:
    def __init__(self) -> None:
        self.provider = settings.llm_provider.lower()
        self.api_key = settings.llm_api_key
        self.model = settings.llm_model
        self.base_url = settings.llm_base_url.rstrip("/")
        self.timeout = settings.llm_timeout_seconds

    def is_configured(self) -> bool:
        if self.provider == "ollama":
            return True
        return bool(self.api_key and self.api_key.strip())

    async def generate_advisory_rewrite(
        self, prompt: str, target_domain: str = "general"
    ) -> dict[str, Any]:
        if not self.is_configured():
            return {
                "available": False,
                "text": "",
                "notes": "Advisory LLM is not configured (LLM_API_KEY unset). Deterministic optimization was applied.",
                "provider": self.provider,
            }

        system_instruction = (
            f"You are a specialized prompt engineering consultant for {target_domain}. "
            "Rewrite the user prompt to maximize clarity, explicit constraints, and structured output. "
            "Output only the optimized prompt text without conversational preamble."
        )

        try:
            async with httpx.AsyncClient(timeout=self.timeout) as client:
                if self.provider in ("openai-compatible", "openai"):
                    headers = {
                        "Authorization": f"Bearer {self.api_key}",
                        "Content-Type": "application/json",
                    }
                    payload = {
                        "model": self.model,
                        "messages": [
                            {"role": "system", "content": system_instruction},
                            {"role": "user", "content": prompt},
                        ],
                        "temperature": 0.3,
                    }
                    resp = await client.post(
                        f"{self.base_url}/chat/completions",
                        headers=headers,
                        json=payload,
                    )
                    resp.raise_or_return_status = resp.raise_for_status()
                    data = resp.json()
                    content = data["choices"][0]["message"]["content"].strip()
                    return {
                        "available": True,
                        "text": content,
                        "notes": f"Advisory rewrite generated by {self.provider} ({self.model}).",
                        "provider": self.provider,
                    }

                elif self.provider == "anthropic":
                    headers = {
                        "x-api-key": self.api_key or "",
                        "anthropic-version": "2023-06-01",
                        "Content-Type": "application/json",
                    }
                    payload = {
                        "model": self.model,
                        "system": system_instruction,
                        "messages": [{"role": "user", "content": prompt}],
                        "max_tokens": 2048,
                        "temperature": 0.3,
                    }
                    resp = await client.post(
                        f"{self.base_url}/v1/messages",
                        headers=headers,
                        json=payload,
                    )
                    resp.raise_for_status()
                    data = resp.json()
                    content = data["content"][0]["text"].strip()
                    return {
                        "available": True,
                        "text": content,
                        "notes": f"Advisory rewrite generated by Anthropic ({self.model}).",
                        "provider": self.provider,
                    }

                elif self.provider == "gemini":
                    # Google Gemini generateContent
                    url = f"{self.base_url}/v1beta/models/{self.model}:generateContent"
                    headers = {"Content-Type": "application/json"}
                    params = {"key": self.api_key} if self.api_key else {}
                    payload = {
                        "system_instruction": {"parts": [{"text": system_instruction}]},
                        "contents": [{"parts": [{"text": prompt}]}],
                    }
                    resp = await client.post(url, headers=headers, params=params, json=payload)
                    resp.raise_for_status()
                    data = resp.json()
                    content = data["candidates"][0]["content"]["parts"][0]["text"].strip()
                    return {
                        "available": True,
                        "text": content,
                        "notes": f"Advisory rewrite generated by Gemini ({self.model}).",
                        "provider": self.provider,
                    }

                elif self.provider == "ollama":
                    payload = {
                        "model": self.model,
                        "prompt": f"{system_instruction}\n\nUser Prompt:\n{prompt}",
                        "stream": False,
                    }
                    resp = await client.post(
                        f"{self.base_url}/api/generate",
                        json=payload,
                    )
                    resp.raise_for_status()
                    data = resp.json()
                    content = data.get("response", "").strip()
                    return {
                        "available": True,
                        "text": content,
                        "notes": f"Advisory rewrite generated by local Ollama ({self.model}).",
                        "provider": self.provider,
                    }

                else:
                    return {
                        "available": False,
                        "text": "",
                        "notes": f"Unsupported LLM provider '{self.provider}'. Supported: openai-compatible, anthropic, gemini, ollama.",
                        "provider": self.provider,
                    }

        except httpx.HTTPStatusError as err:
            status_code = err.response.status_code if err.response else "unknown"
            return {
                "available": False,
                "text": "",
                "notes": f"Provider HTTP error {status_code}: request rejected or credentials invalid.",
                "provider": self.provider,
            }
        except Exception as err:
            clean_err = str(err).replace(self.api_key or "N/A", "[REDACTED]")
            return {
                "available": False,
                "text": "",
                "notes": f"LLM connection error: {clean_err[:120]}",
                "provider": self.provider,
            }
